### ISSUE TITLE
Specify application/json+otrp as media type

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/OTrP#6]
Per agreement in httpbis WG, https://tools.ietf.org/html/draft-ietf-httpbis-bcp56bis-08 section 4.8 says we SHOULD use our own media type (application/json+otrp) instead of the generic application/json.

https://tools.ietf.org/html/draft-thaler-teep-otrp-over-http-00#section-9 contains IANA considerations text to define application/json_otrp but it should be moved to the OTrP spec.

**Comment by mingpeiwk** [comment]
Added in OTrP spec.

**Comment by mingpeiwk** [comment]
Fixed with -03 version now.
